unit intf.ZUGFeRDDateTypeCodes;

interface

uses
  System.SysUtils,
  intf.ZUGFeRDHelper;

// UNTID 2475 codes
//

type
  TZUGFeRDDateTypeCodes = (
    {.DefinitionStart}
    // automatically converted by PSC#ToDelphiDefinition

    /// <summary>
    /// Date of invoice
    /// </summary>
    [EnumStringValue('5')]
    InvoiceDate = 5,

    /// <summary>
    /// Date of delivery of goods to establishments/domicile/site
    /// </summary>
    [EnumStringValue('29')]
    DeliveryDate = 29,

    /// <summary>
    /// Payment date
    /// </summary>
    [EnumStringValue('72')]
    PaymentDate = 72,



    /// <summary>
    /// Unknown value
    /// </summary>
    Unknown
    {.DefinitionEnd}
  );

implementation

procedure Map (EnumValue: TZUGFeRDDateTypeCodes; StringValue: string); inline;
begin
  TEnumExtensions<TZUGFeRDDateTypeCodes>.RegisterMapping(EnumValue, StringValue)
end;

procedure InitMapping;
begin
  {.MapStart}
  // Mapping generated by PSDelphiDefinitionMapper
  Map(InvoiceDate,  '5');
  Map(DeliveryDate, '29');
  Map(PaymentDate,  '72');
  Map(Unknown,      'Unknown');
{.MapEnd}
end;

Initialization
  InitMapping;
end.
