{* Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.}

unit intf.ZUGFeRDVersion;

interface

uses
  System.SysUtils,
  intf.ZUGFeRDHelper;

type
    /// <summary>
    /// Enumeration of the different ZUGFeRD versions supported by ZUGFeRD-csharp
    /// </summary>
  TZUGFeRDVersion = (
    {.DefinitionStart}
    // automatically converted by PSC#ToDelphiDefinition

    /// <summary>
    /// Version 1.x - first public ZUGFeRD version
    /// </summary>
    Version1 = 100,

    /// <summary>
    /// Version 2.0 - second major ZUGFeRD version 
    /// </summary>
    Version20 = 200,

    /// <summary>
    /// Version 2.3 - unified with french factur-x 1.0, supports XRechnung
    /// </summary>
    Version23 = 230,


    /// <summary>
    /// Unknown value
    /// </summary>
    Unknown
    {.DefinitionEnd}
  );

implementation

procedure Map (EnumValue: TZUGFeRDVersion; StringValue: string); inline;
begin
  TEnumExtensions<TZUGFeRDVersion>.RegisterMapping(EnumValue, StringValue)
end;

procedure InitMapping;
begin
  {.MapStart}
  // Mapping generated by PSDelphiDefinitionMapper
  Map(Version1,  'Version1');
  Map(Version20, 'Version20');
  Map(Version23, 'Version23');
  Map(Unknown,   'Unknown');
{.MapEnd}
end;

Initialization
  InitMapping;
end.
