{* Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.}

unit intf.ZUGFeRDSpecialServiceDescriptionCodes;

interface

uses
  System.SysUtils,
  intf.ZUGFeRDHelper;

type
  /// <summary>
  /// https://www.xrepository.de/details/urn:xoev-de:kosit:codeliste:untdid.7161_3
  /// </summary>
  TZUGFeRDSpecialServiceDescriptionCodes = (
    {.DefinitionStart}
    AA_Advertising, //The service of providing advertising.
    AAA_Telecommunication, //The service of providing telecommunication activities and/or faclities.
    ABK_Miscellaneous,	//Miscellaneous services.
    ABL_AdditionalPackaging, //The service of providing additional packaging.
    ADR_OtherServices, //A code indicating that other non-specific services are in operation.
    ADT_Pickup, //The service of picking up or collection of goods.
    FC_FreightService, //The service of moving goods, by whatever means, from one place to another.
    FI_Financing, //The service of providing financing.
    LA_Labelling, //Labelling service.
    PC_Packing, //The service of packing.
    TAC_Testing, //The service of testing
    Unknown
    {.DefinitionEnd}
  );

implementation

procedure Map (EnumValue: TZUGFeRDSpecialServiceDescriptionCodes; StringValue: string); inline;
begin
  TEnumExtensions<TZUGFeRDSpecialServiceDescriptionCodes>.RegisterMapping(EnumValue, StringValue)
end;

procedure InitMapping;
begin
  {.MapStart}
  // Mapping generated by PSDelphiDefinitionMapper
  Map(AA_Advertising,          'AA');
  Map(AAA_Telecommunication,   'AAA');
  Map(ABK_Miscellaneous,       'ABK');
  Map(ABL_AdditionalPackaging, 'ABL');
  Map(ADR_OtherServices,       'ADR');
  Map(ADT_Pickup,              'ADT');
  Map(FC_FreightService,       'FC');
  Map(FI_Financing,            'FI');
  Map(LA_Labelling,            'LA');
  Map(PC_Packing,              'PC');
  Map(TAC_Testing,             'TAC');
  Map(Unknown,                 'Unknown');
  {.MapEnd}
end;

Initialization
  InitMapping;
end.
