{* Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.}

unit intf.ZUGFeRDAccountingAccountTypeCodes;

interface

uses
  System.SysUtils,
  intf.ZUGFeRDHelper;

type
  //based on https://www.unece.org/fileadmin/DAM/uncefact/codelist/standard/EDIFICASEU_AccountingAccountType_D11A.xsd

  /// <summary>Account Types (EDIFICAS-EU Code List)</summary>
  TZUGFeRDAccountingAccountTypeCodes = (
    {.DefinitionStart}
    // automatically converted by PSC#ToDelphiDefinition

    /// <summary>
    /// The code indicates a financial account
    /// </summary>
    [EnumStringValue('1')]
    Financial = 1,

    /// <summary>
    /// The code indicates a subsidiary account
    /// </summary>
    [EnumStringValue('2')]
    Subsidiary = 2,

    /// <summary>
    /// The code indicates a budget account
    /// </summary>
    [EnumStringValue('3')]
    Budget = 3,

    /// <summary>
    /// The code indicates a cost accounting account
    /// </summary>
    [EnumStringValue('4')]
    Cost_Accounting = 4,

    /// <summary>
    /// The code indicates a receivable account
    /// </summary>
    [EnumStringValue('5')]
    Receivable = 5,

    /// <summary>
    /// The code indicates a payable account
    /// </summary>
    [EnumStringValue('6')]
    Payable = 6,

    /// <summary>
    /// The code indicates a job cost accounting
    /// </summary>
    [EnumStringValue('7')]
    Job_Cost_Accounting = 7,


    /// <summary>
    /// Unknown value
    /// </summary>
    Unknown
    {.DefinitionEnd}
  );

implementation

procedure Map (EnumValue: TZUGFeRDAccountingAccountTypeCodes; StringValue: string); inline;
begin
  TEnumExtensions<TZUGFeRDAccountingAccountTypeCodes>.RegisterMapping(EnumValue, StringValue)
end;

procedure InitMapping;
begin
  {.MapStart}
  // Mapping generated by PSDelphiDefinitionMapper
  Map(Financial,           '1');
  Map(Subsidiary,          '2');
  Map(Budget,              '3');
  Map(Cost_Accounting,     '4');
  Map(Receivable,          '5');
  Map(Payable,             '6');
  Map(Job_Cost_Accounting, '7');
  Map(Unknown,             'Unknown');
{.MapEnd}
end;

Initialization
  InitMapping;
end.
